FROM registry.access.redhat.com/ubi9/ubi:latest AS update
RUN python3 -m ensurepip && \
    python3 -m pip install ruamel.yaml

COPY hack/konflux .
COPY bundle/manifests /manifests/
COPY bundle/metadata /metadata/

RUN source ./container_digest.sh && source ./bundle_vars.sh && python3 ./update_bundle.py

FROM scratch

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=openshift-cudn-bgp-routing
LABEL operators.operatorframework.io.bundle.channels.v1=alpha
LABEL operators.operatorframework.io.bundle.channel.default.v1=alpha
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.42.2
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v4

LABEL maintainer="Red Hat, Inc."
LABEL com.redhat.component="bgp-cloud-connector-bundle"
LABEL name="bgp-cloud-connector/bgp-cloud-connector-bundle"

COPY --from=update /manifests /manifests/
COPY --from=update /metadata /metadata/
