FROM registry.access.redhat.com/ubi9/go-toolset:1.26.5-1786351949 as builder
WORKDIR /workspace
# Dummy RUN to create /workspace directory.
# WORKDIR doesn't create the directory (at least for Podman).
# Without this step, the following COPY may create /workspace
# as root-owned (instead of go-toolset's default 1001)
# leading to "Permission denied" errors during "make build-operator"
# when trying to write output.
RUN ls .
COPY . /workspace
RUN git config --global --add safe.directory /workspace
# Build
RUN make build-operator

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:48fa5d8cda7fc00d270d8747c3eaa54ae196f0820d8540074a9c8c61d5e3056f
LABEL maintainer="Red Hat, Inc."
LABEL com.redhat.component="bgp-cloud-connector-operator"
LABEL name="bgp-cloud-connector/bgp-cloud-connector-operator"
WORKDIR /
COPY --from=builder /workspace/bin/manager /
COPY LICENSE /licenses/
USER 65532:65532
ENTRYPOINT ["/manager"]
